#!/bin/bash

set -e

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database /usr/share/applications
fi

# Update icon cache
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache -f -t /usr/share/pixmaps
    /usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor
fi

# Reload polkit rules
if [ -x /usr/bin/systemctl ]; then
    /usr/bin/systemctl try-reload-or-restart polkit
fi

exit 0